apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapimysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todomysql
  template:
    metadata:
      labels:
        app: todomysql
    spec:
      containers:
      - name: todoapimysql
        image: myusername/todoapimysql:1.0
        env:
        - name: MYSQL_HOST
          value: svcmysql.default.svc.cluster.local
        ports:
        - containerPort: 80




---


apiVersion: v1
kind: Service
metadata:
  name: svctodomysqlapi
spec:
  type: NodePort
  selector:
    app: todomysql
  ports:
  - port: 9098
    targetPort: 80


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_DATABASE
          value: tododb
        - name: MYSQL_ROOT_PASSWORD
          value: P@ssw0rd
        ports:
        - containerPort: 3306


---


apiVersion: v1
kind: Service
metadata:
  name: svcmysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
